Algorithms/CPP/Kruskals.cpp

Well commented C++ implementation of Kruskal's Algorithm.

Add code for Kruskals Algorithm

---

Algorithms/JAVA/Search Algorithm/BinaryTree.java
Algorithms/JAVA/Search Algorithm/inorder.java
Algorithms/JAVA/Search Algorithm/postorder.java
Algorithms/JAVA/Search Algorithm/preorder.java

I have added a binary search tree, Inorder, Postorder, and preorder using stack operations and normal operations.

Binary search Tree using Java

---

Algorithms/JAVA/InsertionSort.java

Added a simple code for insertion sort in java also gave an input-output example as a comment below the code. Would love to contribute more to this repo in the future:)

added Insertion sort for java

---

Algorithms/CPP/Array in spiral order.cpp

Print 2-D matrix in spiral order

---

Algorithms/CPP/Dijkstra's_Algo.cpp

Dijkstra's Algorithm added in Algorithm folder in cpp

Dijkstra's Algorithm in cpp

---

Algorithms/C#/Sorting/BubbleSort.cs

Bubble sort algorithm in C# added.

---

Algorithms/C/pascals_triangle.c

I have made a PR for adding the Algorithm for printing Pascals Triangle in C, For the issue #2  . Please merge it.

Added Pascals Triangle program in C

---

Algorithms/C/Quick_sort.c
Placements/Arrays/1. Linera Search.md
Placements/Arrays/10. Find equilibrium index.md
Placements/Arrays/11. Find the maximum element for each and every contiguous subarray of size K.md
Placements/Arrays/12. Count smaller elements on right side.md
Placements/Arrays/13. Find the largest multiple of 3.md
Placements/Arrays/14. Find subarray with given sum.md
Placements/Arrays/15. Find the largest subarray with equal number of 0's & 1's.md
Placements/Arrays/16. Product of array without using division operator.md
Placements/Arrays/17. Sort a nearly sorted (or K sorted) array.md
Placements/Arrays/18. Find duplicates in O(n) time and O(1) extra space.md
Placements/Arrays/19. Find the two repeating elements in a given array.md
Placements/Arrays/2. Binary Search.md
Placements/Arrays/20. Sort an array in wave form.md
Placements/Arrays/21. Find next greater number with same set of digits.md
Placements/Arrays/22. Trapping Rain Water.md
Placements/Arrays/23. Count the number of possible triangles.md
Placements/Arrays/24. Smallest positive integer value that cannot be represented as sum of any subset..md
Placements/Arrays/25. Rearrange an array so that arr[i] becomes arr[arr[i]] with O(1) extra space.md
Placements/Arrays/26. Rotate a matrix by 90 degree in clockwise direction without using any extra space.md
Placements/Arrays/3. Pair with sum k.md
Placements/Arrays/4. Majority Element.md
Placements/Arrays/5. Max Difference Large after Small element.md
Placements/Arrays/6. Find number with odd occurance.md
Placements/Arrays/7. Seperate 0's and 1's in an array.md
Placements/Arrays/8. Find the element who's sum is cloest to 0.md
Placements/Arrays/9. Find triplate with sum x.md
Placements/README.md

Hi! 
I have added the Standard CP question for arrays important from placement point of view.
All the markdown file consists of following structure:
- Problem statement
- Algorithm
- Code

Added Standard CP question.

---

DAV/arthimetic operator.py
DAV/circle area.py

bhaiya DAv wala folder nhi aa rha tha isliye maine khud ek DAV ka folder bna diya

arthimetic operator program DAV

---

Algorithms/C/special_diamond_pattern.c
Algorithms/Python/special_diamond_pattern.py

#2 
I have added a special diamond pattern implementation in both C and Python Language
What makes this pattern special :
1 Single loop 
2 Single if else-if ladder
3 Only 3 variables in whole program
@apoorvdwi 
Please merge this PR 😀

Special diamond pattern

---

Placements/Strings/47's Strings.cpp
Placements/Strings/Ashish and Binary Matrix.cpp
Placements/Strings/BinarySwap.cpp
Placements/Strings/Can you count.cpp
Placements/Strings/Harry and String.cpp
Placements/Strings/Lexical Analyzer.cpp
Placements/Strings/Marut and Strings.cpp
Placements/Strings/Mirror of Mahatma Gandhi.CPP
Placements/Strings/NameGame.cpp
Placements/Strings/Password.cpp
Placements/Strings/Remove Duplicates.cpp
Placements/Strings/SecretMessage.cpp
Placements/Strings/StringInBinary.cpp
Placements/Strings/Terrible Chandu.cpp
Placements/Strings/UniqueSubsequence.cpp
Placements/Strings/UpUp.cpp

HackerEarth Solution

---

Computer Graphics/DIGITAL.CPP
Computer Graphics/RAINBOW.CPP

added rainbow and digital clock using computer graphics

computer graphics

---

dav/Use of various airthmetical operators of Python.py
dav/dictionary.py
dav/to calculate the cost of tent for wedding.py
dav/various operations with numbers in python.py

https://github.com/apoorvdwi/Ds-Algo-HacktoberFest/pull/52/commits/7a7c5346e214d3bc5a943599ab93ed15643fd623
https://github.com/apoorvdwi/Ds-Algo-HacktoberFest/pull/52/commits/8cb036b0dd265e52b0070e2bfec5878dc155ea39
https://github.com/apoorvdwi/Ds-Algo-HacktoberFest/pull/52/commits/7e6d28e7d173d73eeba90117642ffeb4a13133ac
https://github.com/apoorvdwi/Ds-Algo-HacktoberFest/pull/52/commits/118d5c097415177493757faee48811b6ee66e080
these are the four files uploaded by me

oxford dictionary in python computer language

---

Algorithms/Python/Randompasswordgenerator.py

uses special and alphanumeric characters to create a strong passwords.

Password_generator.py

---

Machine Learning/Models/1-titanic-solution.ipynb

I have made a PR of Titanic Survival Prediction with exploratory data analysis.
@apoorvdwi Kindly merge my request.

Added a notebook of Titanic Survival Prediction

---

Data Structures/Python/linked_list.py

I have made a PR for linked list implementation in Python 3.
@apoorvdwi Please Merge my PR.

Added linked list program in python3

---

Machine Learning/Models/Twitter_Sentiment_Analysis_using_Logistic_Regression.ipynb

I have added a python notebook of Twitter Tweets Analysis using Logistic Regression and NLP.
@apoorvdwi kindly merge my PR.

Added python notebook of Twitter Tweets Analysis using Logistic Regression and NLP

---

Data Structures/CPP/tree.cpp

Tree Structure Implementation in cpp

Added tree.cpp

---

Machine Learning/Algorithms/K-Nearest-Neighbours.py

K-Nearest-Neighbours Algorithm for Machine Learning

Added K-Nearest-Neighbours.py

---

Algorithms/JAVA/Selection_sort.java

Selection sort for java

---

DAV/Age Calculator.c

I have added a Age Calculator in C.
@apoorvdwi  Kindly merge my PR

Added a program of Age Calculation using C

---

Algorithms/C/inserting elements in beginning in linked list.c

I have added a file of insertion of element in linked list at the beginning.
@apoorvdwi kindly merge my PR

Added a C file of insertion of element in linked list at beginning

---

Placements/Codechef/Beginner/README.md.txt
Placements/Codechef/Beginner/TOWIN.py
Placements/Codechef/Beginner/TREE2.cpp
Placements/Codechef/Easy/CLEANUP.CPP
Placements/Codechef/Easy/JOHNY.CPP
Placements/Codechef/Easy/MARCHA1.py
Placements/Codechef/Easy/README.md.txt
Placements/Codechef/README.md.txt

Codechef folder added in the Placement directory
Text files changed to their subsequent language files.
PR recreated
Thank You

Codechef solutions added

---

Algorithms/JAVA/MergeSort.java

I have added a program of Merge Sort using java

Added a Java file of Merge sort

---

Machine Learning/Algorithms/Decision_Tree_Regression/Decision_Tree_Regression.csv
Machine Learning/Algorithms/Decision_Tree_Regression/Decision_Tree_Regression.py

Added a folder for decision tree regression containing the python script and the dataset in machinelearning/algorithm

Added Decision tree Regression

---

Algorithms/CPP/Krishnamurthy Number/Krishnamurthy_number.cpp
Algorithms/CPP/Krishnamurthy Number/readme.md

To check if a Number is Krishnamurthy Number or not

Algorith to check Krishnamurthy Number
